#!/bin/bash
# ============================================
# Pi-hole Blocklist Builder
# ============================================
# This script combines all individual blocklists
# into a single unified file, removes duplicates,
# and validates the format.
#
# Usage: ./build.sh
# ============================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOSTS_DIR="${SCRIPT_DIR}/hosts"
OUTPUT_FILE="${SCRIPT_DIR}/hosts/combined"

echo "🔨 Pi-hole Blocklist Builder"
echo "============================================"

# Validate hosts directory exists
if [ ! -d "$HOSTS_DIR" ]; then
    echo "❌ Error: hosts/ directory not found!"
    exit 1
fi

# Create combined header
cat > "$OUTPUT_FILE" << 'EOF'
# ============================================
# Combined Blocklist for Pi-hole
# Auto-generated — DO NOT EDIT MANUALLY
# ============================================
# This file is generated by build.sh
# It combines all individual blocklists into
# a single unified file for convenience.
#
# Individual lists available:
#   - ads-tracking    : Ads & tracking domains
#   - ai              : AI Chatbots & Image Generators
#   - facebook        : Facebook & Meta services
#   - gambling        : Gambling & betting sites
#   - gaming          : Mobile, PC & web games
#   - instagram       : Instagram
#   - malware-phishing: Malware & security threats
#   - porn            : Adult content (18+)
#   - snapchat        : Snapchat
#   - tiktok          : TikTok & ByteDance
#   - twitter         : Twitter/X
#   - whatsapp        : WhatsApp
#   - youtube         : YouTube (full block)
#   - youtubeAds      : YouTube ads only
# ============================================
EOF

# Add generation timestamp
echo "# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$OUTPUT_FILE"
echo "# ============================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Count stats
total_files=0
total_entries=0

# Process each host file (exclude the combined file itself)
for file in "$HOSTS_DIR"/*; do
    filename=$(basename "$file")
    
    # Skip the combined file itself
    if [ "$filename" = "combined" ]; then
        continue
    fi
    
    if [ -f "$file" ]; then
        # Count non-comment, non-empty lines
        count=$(grep -cE '^0\.0\.0\.0\s' "$file" 2>/dev/null || echo "0")
        total_entries=$((total_entries + count))
        total_files=$((total_files + 1))
        
        echo "  ✅ $filename ($count entries)"
        
        # Add section header and content (only non-comment, non-empty lines)
        echo "" >> "$OUTPUT_FILE"
        echo "# --- $filename ---" >> "$OUTPUT_FILE"
        grep -E '^0\.0\.0\.0\s' "$file" >> "$OUTPUT_FILE" 2>/dev/null || true
    fi
done

echo ""
echo "============================================"

# Remove duplicate entries (keep first occurrence)
before_dedup=$(grep -cE '^0\.0\.0\.0\s' "$OUTPUT_FILE" 2>/dev/null || echo "0")
temp_file=$(mktemp)

# Separate headers/comments from entries, deduplicate entries
grep -v '^0\.0\.0\.0\s' "$OUTPUT_FILE" > "$temp_file"
grep '^0\.0\.0\.0\s' "$OUTPUT_FILE" | sort -u >> "$temp_file"
mv "$temp_file" "$OUTPUT_FILE"

after_dedup=$(grep -cE '^0\.0\.0\.0\s' "$OUTPUT_FILE" 2>/dev/null || echo "0")
duplicates=$((before_dedup - after_dedup))

echo "📊 Summary:"
echo "   Files processed: $total_files"
echo "   Total entries:   $before_dedup"
echo "   Duplicates:      $duplicates"
echo "   Unique entries:  $after_dedup"
echo ""
echo "📁 Output: $OUTPUT_FILE"
echo "============================================"
echo "✨ Done!"
